
import { Prompt, Translations } from './types';

export const PROMPTS: Prompt[] = [
  {
    id: '1',
    title_en: 'Generate Marketing Campaign Strategy',
    title_fa: 'استراتژی کمپین بازاریابی تولید کنید',
    category: 'Marketing',
    industry: 'E-commerce',
    role: 'Marketing Manager',
    prompt_en: `**Persona:** You are a world-class Marketing Strategist with expertise in launching sustainable consumer products.\n\n**Objective:** Generate a comprehensive marketing campaign strategy for the launch of "TerraStride," a new line of premium, eco-friendly sneakers made from recycled materials.\n\n**Context:** The target market is environmentally conscious millennials and Gen Z (ages 18-35) who value style, durability, and sustainability. The brand's core message is "Walk the Talk." The budget is moderate.\n\n**Task:**\n1.  **Core Campaign Concepts (3 options):** Develop three distinct, creative campaign concepts. For each, provide a catchy tagline and outline the central narrative.\n2.  **Channel Strategy:** Specify key digital platforms (Instagram, TikTok) and content types (e.g., Reels showing the recycling process, influencer partnerships with eco-activists). Suggest one experiential pop-up event idea.\n3.  **Key Messaging:** Draft three key messages highlighting sustainability, style, and comfort. Write a sample Instagram caption.\n4.  **Measurement:** Suggest 3 key performance indicators (KPIs) to measure success.\n\n**Constraints:** The tone must be inspiring, authentic, and slightly edgy. Avoid corporate jargon. The output must be in well-structured Markdown.`,
    prompt_fa: `**شخصیت:** شما یک استراتژیست بازاریابی در سطح جهانی با تخصص در عرضه محصولات مصرفی پایدار هستید.\n\n**هدف:** یک استراتژی کمپین بازاریابی جامع برای عرضه "TerraStride"، خط جدیدی از کفش‌های ورزشی دوستدار محیط زیست و باکیفیت که از مواد بازیافتی ساخته شده‌اند، تولید کنید.\n\n**زمینه:** بازار هدف، نسل‌های هزاره و Z (سنین ۱۸ تا ۳۵ سال) آگاه به محیط زیست هستند که برای سبک، دوام و پایداری ارزش قائلند. پیام اصلی برند "به عمل کار برآید" است. بودجه متوسط است.\n\n**وظیفه:**\n۱. **مفاهیم اصلی کمپین (۳ گزینه):** سه مفهوم کمپین خلاقانه و متمایز توسعه دهید. برای هر کدام، یک شعار جذاب ارائه دهید و روایت اصلی را تشریح کنید.\n۲. **استراتژی کانال:** پلتفرم‌های دیجیتال کلیدی (اینستاگرام، تیک‌تاک) و انواع محتوا (مانند Reels که فرآیند بازیافت را نشان می‌دهد، همکاری با اینفلوئنسرهای فعال محیط زیست) را مشخص کنید. یک ایده برای رویداد پاپ-آپ تجربی پیشنهاد دهید.\n۳. **پیام‌رسانی کلیدی:** سه پیام کلیدی که مزایای پایداری، سبک و راحتی را برجسته می‌کنند، پیش‌نویس کنید. یک نمونه کپشن اینستاگرام بنویسید.\n۴. **اندازه‌گیری:** ۳ شاخص کلیدی عملکرد (KPI) برای اندازه‌گیری موفقیت پیشنهاد دهید.\n\n**محدودیت‌ها:** لحن باید الهام‌بخش، معتبر و کمی جسورانه باشد. از اصطلاحات شرکتی خودداری کنید. خروجی باید با فرمت Markdown ساختاریافته باشد.`,
    tags_en: ['strategy', 'e-commerce', 'sustainability'],
    tags_fa: ['استراتژی', 'تجارت الکترونیک', 'پایداری'],
  },
  {
    id: '2',
    title_en: 'Draft Detailed HR Onboarding Plan',
    title_fa: 'پیش‌نویس برنامه جامع آنبوردینگ منابع انسانی',
    category: 'HR',
    industry: 'Technology',
    role: 'HR Specialist',
    prompt_en: `**Persona:** You are an experienced HR Onboarding Specialist at a fast-growing tech company.\n\n**Objective:** Create a detailed and engaging 30-day onboarding plan for a new remote Senior Software Engineer.\n\n**Context:** The new hire needs to be integrated into the team, understand the company culture, and become productive quickly. They will be working on the "Core Platform" team.\n\n**Task:**\n1.  **Week 1 (Orientation & Setup):** Outline daily activities, including required paperwork, tech setup, introductory meetings with key team members (manager, mentor, teammates), and an overview of the company's mission and values.\n2.  **Week 2 (Learning & Integration):** Detail the plan for learning the tech stack, codebase, and development processes. Suggest a small, non-critical first task. Schedule a virtual team lunch.\n3.  **Weeks 3-4 (Contribution & Feedback):** Define how the new hire will start contributing to the current sprint. Schedule a 30-day check-in meeting with their manager to discuss progress and gather feedback.\n4.  **Documentation:** List essential documents the new hire should read (e.g., engineering best practices, product roadmap, team charter).\n\n**Constraints:** The plan should be structured as a timeline in Markdown. The tone should be welcoming, organized, and professional.`,
    prompt_fa: `**شخصیت:** شما یک متخصص آنبوردینگ منابع انسانی باتجربه در یک شرکت فناوری در حال رشد سریع هستید.\n\n**هدف:** یک برنامه آنبوردینگ ۳۰ روزه دقیق و جذاب برای یک مهندس نرم‌افزار ارشد جدید که به صورت دورکار استخدام شده است، ایجاد کنید.\n\n**زمینه:** کارمند جدید باید در تیم ادغام شود، فرهنگ شرکت را درک کند و به سرعت به بهره‌وری برسد. او در تیم "پلتفرم اصلی" کار خواهد کرد.\n\n**وظیفه:**\n۱. **هفته اول (آشنایی و راه‌اندازی):** فعالیت‌های روزانه را تشریح کنید، شامل مدارک مورد نیاز، راه‌اندازی فنی، جلسات معارفه با اعضای کلیدی تیم (مدیر، مربی، هم‌تیمی‌ها) و مروری بر مأموریت و ارزش‌های شرکت.\n۲. **هفته دوم (یادگیری و ادغام):** برنامه یادگیری پشته فناوری، کدبیس و فرآیندهای توسعه را جزئی‌نگاری کنید. یک وظیفه اولیه کوچک و غیرحیاتی پیشنهاد دهید. یک ناهار تیمی مجازی برنامه‌ریزی کنید.\n۳. **هفته‌های ۳-۴ (مشارکت و بازخورد):** نحوه شروع مشارکت کارمند جدید در اسپرینت فعلی را تعریف کنید. یک جلسه بررسی ۳۰ روزه با مدیر او برای بحث در مورد پیشرفت و جمع‌آوری بازخورد برنامه‌ریزی کنید.\n۴. **مستندات:** لیستی از اسناد ضروری که کارمند جدید باید بخواند (مانند بهترین شیوه‌های مهندسی، نقشه راه محصول، منشور تیم) تهیه کنید.\n\n**محدودیت‌ها:** برنامه باید به صورت یک جدول زمانی در Markdown ساختاریافته باشد. لحن باید خوش‌آمدگو، سازمان‌یافته و حرفه‌ای باشد.`,
    tags_en: ['onboarding', 'remote work', 'HR'],
    tags_fa: ['آنبوردینگ', 'کار از راه دور', 'منابع انسانی'],
  },
  {
    id: '3',
    title_en: 'Create a DevOps Post-Incident Report',
    title_fa: 'ایجاد گزارش پس از حادثه DevOps',
    category: 'DevOps',
    industry: 'Finance',
    role: 'DevOps Engineer',
    prompt_en: `**Persona:** You are a meticulous Site Reliability Engineer (SRE).\n\n**Objective:** Generate a comprehensive post-incident report (PIR) for a critical database outage.\n\n**Context:** On 2023-10-27 at 14:30 UTC, the primary customer database became unresponsive, causing a 45-minute complete service outage. The issue was resolved by failing over to the replica database.\n\n**Task:** Create a PIR document using the following structure:\n1.  **Summary:** A high-level overview including impact (what happened), duration, and resolution.\n2.  **Timeline:** A detailed, timestamped log of events from detection to resolution, including key actions taken and communications sent.\n3.  **Root Cause Analysis (RCA):** A deep dive into the technical cause. Hypothesize that a runaway query consumed all available memory, triggering the outage.\n4.  **Resolution:** Describe the steps taken to restore the service.\n5.  **Action Items / Preventative Measures:** Propose at least three concrete, actionable steps to prevent recurrence. Assign a priority (P0, P1, P2) and a suggested owner for each (e.g., "Database Team").\n\n**Constraints:** The report must be blameless, focusing on systems and processes, not people. Use a formal, technical tone. Format as a Markdown document.`,
    prompt_fa: `**شخصیت:** شما یک مهندس قابلیت اطمینان سایت (SRE) دقیق هستید.\n\n**هدف:** یک گزارش جامع پس از حادثه (PIR) برای یک قطعی حیاتی پایگاه داده ایجاد کنید.\n\n**زمینه:** در تاریخ ۲۷-۱۰-۲۰۲۳ ساعت ۱۴:۳0 UTC، پایگاه داده اصلی مشتریان غیرپاسخگو شد و باعث قطعی کامل سرویس به مدت ۴۵ دقیقه گردید. مشکل با انتقال به پایگاه داده جایگزین (replica) حل شد.\n\n**وظیفه:** یک سند PIR با استفاده از ساختار زیر ایجاد کنید:\n۱. **خلاصه:** یک نمای کلی سطح بالا شامل تأثیر (چه اتفاقی افتاد)، مدت زمان و راه‌حل.\n۲. **خط زمانی:** یک گزارش دقیق و زمان‌بندی شده از رویدادها از زمان شناسایی تا حل، شامل اقدامات کلیدی انجام شده و ارتباطات ارسال شده.\n۳. **تحلیل علت ریشه‌ای (RCA):** یک بررسی عمیق از علت فنی. فرض کنید که یک کوئری خارج از کنترل تمام حافظه موجود را مصرف کرده و باعث قطعی شده است.\n۴. **راه‌حل:** مراحل انجام شده برای بازیابی سرویس را شرح دهید.\n۵. **اقدامات عملی / اقدامات پیشگیرانه:** حداقل سه اقدام مشخص و قابل اجرا برای جلوگیری از تکرار پیشنهاد دهید. برای هر کدام یک اولویت (P0, P1, P2) و یک مالک پیشنهادی (مثلاً "تیم پایگاه داده") تعیین کنید.\n\n**محدودیت‌ها:** گزارش باید بدون سرزنش باشد و بر روی سیستم‌ها و فرآیندها تمرکز کند، نه افراد. از لحن رسمی و فنی استفاده کنید. به عنوان یک سند Markdown فرمت‌بندی کنید.`,
    tags_en: ['incident management', 'SRE', 'database'],
    tags_fa: ['مدیریت حوادث', 'SRE', 'پایگاه داده'],
  },
    {
    id: '4',
    title_en: 'Design In-Depth UI/UX Feedback Survey',
    title_fa: 'طراحی نظرسنجی عمیق بازخورد UI/UX',
    category: 'Design',
    industry: 'Healthcare',
    role: 'UX Designer',
    prompt_en: `**Persona:** You are a user-centric UX Researcher.\n\n**Objective:** Design a comprehensive survey to gather qualitative and quantitative feedback on a newly redesigned patient portal dashboard.\n\n**Context:** The goal of the redesign was to improve information accessibility for patients regarding their appointments, test results, and prescriptions. Users are typically non-technical and may range in age from 18 to 70+.\n\n**Task:** Create a survey with 3 sections:\n1.  **Usability & Navigation:** Include questions using a Likert scale (1-5) to rate ease of finding information. Add one open-ended question asking what was most difficult to find.\n2.  **Visual Appeal & Clarity:** Ask users to rate the new design's visual appeal and the clarity of the layout. Include a multiple-choice question asking which element they noticed first.\n3.  **Overall Satisfaction & Suggestions:** Include a Net Promoter Score (NPS) question ("How likely are you to recommend..."). Add two open-ended questions: "What is the single best improvement in the new design?" and "If you could change one thing, what would it be?".\n\n**Constraints:** Keep the survey concise, aiming for a 5-minute completion time. The language should be simple, empathetic, and free of technical jargon.`,
    prompt_fa: `**شخصیت:** شما یک محقق تجربه کاربری کاربرمحور هستید.\n\n**هدف:** طراحی یک نظرسنجی جامع برای جمع‌آوری بازخورد کیفی و کمی در مورد داشبورد پورتال بیماران که به تازگی بازطراحی شده است.\n\n**زمینه:** هدف از بازطراحی، بهبود دسترسی بیماران به اطلاعات مربوط به قرارها، نتایج آزمایش‌ها و نسخه‌هایشان بوده است. کاربران معمولاً غیرفنی هستند و سن آن‌ها می‌تواند از ۱۸ تا ۷۰+ سال متغیر باشد.\n\n**وظیفه:** یک نظرسنجی با ۳ بخش ایجاد کنید:\n۱. **قابلیت استفاده و ناوبری:** شامل سوالاتی با استفاده از مقیاس لیکرت (۱-۵) برای ارزیابی سهولت یافتن اطلاعات. یک سوال باز در مورد اینکه چه چیزی برای یافتن دشوارتر بوده است، اضافه کنید.\n۲. **جذابیت بصری و وضوح:** از کاربران بخواهید جذابیت بصری طراحی جدید و وضوح طرح‌بندی را ارزیابی کنند. یک سوال چندگزینه‌ای در مورد اینکه کدام عنصر را اول متوجه شدند، بگنجانید.\n۳. **رضایت کلی و پیشنهادات:** یک سوال شاخص خالص ترویج‌کنندگان (NPS) ("چقدر احتمال دارد که ... را توصیه کنید؟") اضافه کنید. دو سوال باز دیگر اضافه کنید: "بزرگترین بهبود در طراحی جدید چیست؟" و "اگر می‌توانستید یک چیز را تغییر دهید، آن چه بود؟".\n\n**محدودیت‌ها:** نظرسنجی را مختصر نگه دارید و زمان تکمیل آن را حدود ۵ دقیقه در نظر بگیرید. زبان باید ساده، همدلانه و عاری از اصطلاحات فنی باشد.`,
    tags_en: ['user research', 'survey', 'UX'],
    tags_fa: ['تحقیق کاربری', 'نظرسنجی', 'تجربه کاربری'],
  },
  {
    id: '5',
    title_en: 'Executive Summary of a Technical Whitepaper',
    title_fa: 'خلاصه اجرایی از یک وایت‌پیپر فنی',
    category: 'Education',
    industry: 'Technology',
    role: 'Technical Writer',
    prompt_en: `**Persona:** You are a skilled Technical Writer, adept at translating complex technical concepts into clear, concise business-oriented language.\n\n**Objective:** Create a 300-word executive summary of a technical whitepaper about a new AI-powered data analytics platform.\n\n**Context:** The target audience for the summary is C-level executives (CEO, CTO, CIO) who are not experts in AI but need to understand the business implications.\n\n**Task:** Read the following (placeholder) technical document and distill it into an executive summary. The summary must cover:\n1.  **The Problem:** Briefly state the business problem the platform solves (e.g., "inefficient data processing and lack of predictive insights").\n2.  **The Solution:** Describe the platform at a high level. Focus on *what* it does, not *how* it does it. Mention the core technology (e.g., "proprietary machine learning algorithms").\n3.  **Key Benefits & Differentiators:** List 3-4 key benefits in bullet points (e.g., "Reduces data analysis time by 90%", "Increases forecast accuracy by 30%", "Integrates seamlessly with existing infrastructure").\n4.  **Business Impact:** Conclude with a strong statement about the platform's potential impact on revenue or operational efficiency.\n\n**Placeholder Document:** "[The user will paste the full whitepaper content here. For now, assume it's a 20-page document detailing a complex AI system for financial forecasting.]"\n\n**Constraints:** The word count must be strictly around 300 words. The tone must be professional, confident, and persuasive. Avoid technical jargon entirely.`,
    prompt_fa: `**شخصیت:** شما یک نویسنده فنی ماهر هستید که در ترجمه مفاهیم پیچیده فنی به زبان روشن، مختصر و تجاری‌محور مهارت دارید.\n\n**هدف:** یک خلاصه اجرایی ۳۰۰ کلمه‌ای از یک وایت‌پیپر فنی در مورد یک پلتفرم تحلیل داده جدید مبتنی بر هوش مصنوعی ایجاد کنید.\n\n**زمینه:** مخاطب هدف این خلاصه، مدیران ارشد اجرایی (CEO, CTO, CIO) هستند که متخصص هوش مصنوعی نیستند اما نیاز به درک پیامدهای تجاری آن دارند.\n\n**وظیفه:** سند فنی (جایگزین) زیر را بخوانید و آن را به یک خلاصه اجرایی تبدیل کنید. خلاصه باید موارد زیر را پوشش دهد:\n۱. **مشکل:** به طور خلاصه مشکل تجاری که پلتفرم حل می‌کند را بیان کنید (مثلاً، "پردازش ناکارآمد داده‌ها و کمبود بینش‌های پیش‌بینی‌کننده").\n۲. **راه‌حل:** پلتفرم را در سطح بالا توصیف کنید. بر روی *چه کاری* انجام می‌دهد تمرکز کنید، نه *چگونه*. به فناوری اصلی اشاره کنید (مثلاً، "الگوریتم‌های یادگیری ماشین اختصاصی").\n۳. **مزایا و تمایزات کلیدی:** ۳-۴ مزیت کلیدی را به صورت لیست گلوله‌ای فهرست کنید (مثلاً، "کاهش ۹۰٪ زمان تحلیل داده"، "افزایش ۳۰٪ دقت پیش‌بینی"، "یکپارچه‌سازی بی‌نقص با زیرساخت‌های موجود").\n۴. **تأثیر تجاری:** با یک بیانیه قوی در مورد تأثیر بالقوه پلتفرم بر درآمد یا کارایی عملیاتی نتیجه‌گیری کنید.\n\n**سند جایگزین:** "[کاربر محتوای کامل وایت‌پیپر را اینجا الصاق خواهد کرد. فعلاً فرض کنید این یک سند ۲۰ صفحه‌ای است که یک سیستم هوش مصنوعی پیچیده برای پیش‌بینی مالی را شرح می‌دهد.]"\n\n**محدودیت‌ها:** تعداد کلمات باید دقیقاً حدود ۳۰۰ کلمه باشد. لحن باید حرفه‌ای، بااعتمادبه‌نفس و متقاعدکننده باشد. به طور کامل از اصطلاحات فنی خودداری کنید.`,
    tags_en: ['summarization', 'technical writing', 'AI'],
    tags_fa: ['خلاصه‌سازی', 'نویسندگی فنی', 'هوش مصنوعی'],
  },
  {
    id: '6',
    title_en: 'Analyze Quarterly Financial Report',
    title_fa: 'تحلیل گزارش مالی فصلی',
    category: 'Finance',
    industry: 'Finance',
    role: 'Financial Analyst',
    prompt_en: `**Persona:** You are a senior Financial Analyst reporting to the CFO.\n\n**Objective:** Analyze the attached quarterly financial report and provide key insights for an upcoming board meeting.\n\n**Task:**\n1.  **Performance Summary:** Write a 2-paragraph summary of the overall financial performance, comparing this quarter to the previous quarter (QoQ) and the same quarter last year (YoY).\n2.  **Key Metric Analysis:** For Revenue, Net Profit, and Operating Margin, identify the figures and calculate the QoQ and YoY growth percentages. Present this in a Markdown table.\n3.  **Identify Trends & Anomalies:** Highlight one significant positive trend (e.g., "strong growth in the enterprise segment") and one area of concern (e.g., "rising operational costs").\n4.  **Strategic Recommendations:** Based on your analysis, propose two strategic recommendations for the next quarter.\n\n**Placeholder Data:** "[User will paste financial data here - e.g., income statement, balance sheet excerpts.]"\n\n**Constraints:** The analysis must be data-driven and objective. The tone should be formal and analytical.`,
    prompt_fa: `**شخصیت:** شما یک تحلیلگر مالی ارشد هستید که به مدیر ارشد مالی (CFO) گزارش می‌دهد.\n\n**هدف:** گزارش مالی فصلی پیوست شده را تحلیل کرده و بینش‌های کلیدی برای جلسه هیئت مدیره آینده ارائه دهید.\n\n**وظیفه:**\n۱. **خلاصه عملکرد:** یک خلاصه ۲ پاراگرافی از عملکرد کلی مالی بنویسید و این فصل را با فصل قبل (QoQ) و فصل مشابه سال گذشته (YoY) مقایسه کنید.\n۲. **تحلیل معیارهای کلیدی:** برای درآمد، سود خالص و حاشیه عملیاتی، ارقام را مشخص کرده و درصدهای رشد QoQ و YoY را محاسبه کنید. این را در یک جدول Markdown ارائه دهید.\n۳. **شناسایی روندها و ناهنجاری‌ها:** یک روند مثبت قابل توجه (مثلاً، "رشد قوی در بخش سازمانی") و یک حوزه نگران‌کننده (مثلاً، "افزایش هزینه‌های عملیاتی") را برجسته کنید.\n۴. **توصیه‌های استراتژیک:** بر اساس تحلیل خود، دو توصیه استراتژیک برای فصل آینده پیشنهاد دهید.\n\n**داده‌های جایگزین:** "[کاربر داده‌های مالی را اینجا الصاق خواهد کرد - مثلاً، صورت سود و زیان، گزیده‌هایی از ترازنامه.]"\n\n**محدودیت‌ها:** تحلیل باید داده‌محور و عینی باشد. لحن باید رسمی و تحلیلی باشد.`,
    tags_en: ['financial analysis', 'reporting', 'finance'],
    tags_fa: ['تحلیل مالی', 'گزارش‌دهی', 'مالی'],
  },
  {
    id: '7',
    title_en: 'Write a PRD for a New Mobile App Feature',
    title_fa: 'نوشتن سند نیازمندی‌های محصول (PRD) برای یک ویژگی جدید اپلیکیشن',
    category: 'Product Management',
    industry: 'Technology',
    role: 'Product Manager',
    prompt_en: `**Persona:** You are a detail-oriented Product Manager.\n\n**Objective:** Write a Product Requirements Document (PRD) for a new "Social Share" feature within a photo-editing mobile app.\n\n**Task:** Structure the PRD with the following sections:\n1.  **Introduction & Goal:** What is this feature and what user problem does it solve? What business goal does it support (e.g., "increase user acquisition via viral sharing")?\n2.  **User Stories:** Write at least three user stories from the perspective of the end-user (e.g., "As a user, I want to share my edited photo directly to Instagram Stories so I can show my friends.")\n3.  **Feature Requirements (Functional):** List the core functionalities. Be specific. (e.g., "Tapping the 'Share' icon opens a native share sheet," "The app must pre-populate the share text with a branded hashtag.")\n4.  **Design & UX Requirements:** Describe the user flow and any key UI elements needed.\n5.  **Success Metrics:** How will we measure success? (e.g., "Number of shares per day," "Click-through rate on shared links.")\n\n**Constraints:** The PRD should be clear, unambiguous, and comprehensive enough for designers and engineers to start working. Format in Markdown.`,
    prompt_fa: `**شخصیت:** شما یک مدیر محصول جزئی‌نگر هستید.\n\n**هدف:** یک سند نیازمندی‌های محصول (PRD) برای ویژگی جدید "اشتراک‌گذاری اجتماعی" در یک اپلیکیشن موبایل ویرایش عکس بنویسید.\n\n**وظیفه:** PRD را با بخش‌های زیر ساختار دهید:\n۱. **مقدمه و هدف:** این ویژگی چیست و چه مشکل کاربری را حل می‌کند؟ از چه هدف تجاری پشتیبانی می‌کند (مثلاً، "افزایش جذب کاربر از طریق اشتراک‌گذاری ویروسی")؟\n۲. **داستان‌های کاربری:** حداقل سه داستان کاربری از دیدگاه کاربر نهایی بنویسید (مثلاً، "به عنوان یک کاربر، می‌خواهم عکس ویرایش شده‌ام را مستقیماً در استوری اینستاگرام به اشتراک بگذارم تا دوستانم آن را ببینند.")\n۳. **نیازمندی‌های ویژگی (عملکردی):** عملکردهای اصلی را فهرست کنید. دقیق باشید. (مثلاً، "با ضربه زدن روی آیکون 'اشتراک‌گذاری'، شیت اشتراک‌گذاری نیتیو باز می‌شود،" "اپلیکیشن باید متن اشتراک‌گذاری را با یک هشتگ برند از پیش پر کند.")\n۴. **نیازمندی‌های طراحی و تجربه کاربری:** جریان کاربری و هر عنصر کلیدی UI مورد نیاز را توصیف کنید.\n۵. **معیارهای موفقیت:** چگونه موفقیت را اندازه‌گیری خواهیم کرد؟ (مثلاً، "تعداد اشتراک‌گذاری در روز،" "نرخ کلیک روی لینک‌های به اشتراک گذاشته شده.")\n\n**محدودیت‌ها:** PRD باید واضح، بدون ابهام و به اندازه کافی جامع باشد تا طراحان و مهندسان بتوانند کار را شروع کنند. با فرمت Markdown.`,
    tags_en: ['PRD', 'product management', 'mobile app'],
    tags_fa: ['سند نیازمندی‌ها', 'مدیریت محصول', 'اپلیکیشن موبایل'],
  },
  {
    id: '8',
    title_en: 'Develop a Content Calendar',
    title_fa: 'توسعه تقویم محتوایی',
    category: 'Content Creation',
    industry: 'Education',
    role: 'Content Creator',
    prompt_en: `**Persona:** You are a strategic Content Creator for a YouTube channel focused on teaching data science to beginners.\n\n**Objective:** Develop a one-month content calendar to increase subscriber growth and engagement.\n\n**Task:** Create a 4-week content calendar in a Markdown table with the following columns: \`Week\`, \`Video Title\`, \`Format\`, \`Key Concepts\`, and \`Call to Action (CTA)\`.\n*   **Week 1:** Focus on foundational concepts. (e.g., "What is Data Science? A 10-Minute Intro").\n*   **Week 2:** A practical tutorial. (e.g., "Your First Data Analysis Project with Python Pandas").\n*   **Week 3:** An interview with an expert or a career-focused video. (e.g., "How to Get a Job in Data Science in 2024").\n*   **Week 4:** A more advanced or trending topic. (e.g., "Can ChatGPT Help You Learn SQL?").\nFor each video, specify the format (e.g., "Talking Head Explainer," "Live Coding Tutorial") and the CTA (e.g., "Subscribe for more tutorials," "Download the code from my GitHub").\n\n**Constraints:** The topics should be beginner-friendly but engaging. Ensure a variety of formats.`,
    // FIX: Added a missing comma after the prompt_en property.
    prompt_fa: `**شخصیت:** شما یک تولیدکننده محتوای استراتژیک برای یک کانال یوتیوب هستید که بر آموزش علم داده به مبتدیان تمرکز دارد.\n\n**هدف:** یک تقویم محتوایی یک ماهه برای افزایش رشد مشترکین و تعامل ایجاد کنید.\n\n**وظیفه:** یک تقویم محتوایی ۴ هفته‌ای در یک جدول Markdown با ستون‌های زیر ایجاد کنید: \`هفته\`، \`عنوان ویدیو\`، \`فرمت\`، \`مفاهیم کلیدی\` و \`فراخوان به اقدام (CTA)\`.\n*   **هفته اول:** بر مفاهیم بنیادی تمرکز کنید. (مثلاً، "علم داده چیست؟ یک معرفی ۱۰ دقیقه‌ای").\n*   **هفته دوم:** یک آموزش عملی. (مثلاً، "اولین پروژه تحلیل داده شما با Python Pandas").\n*   **هفته سوم:** مصاحبه با یک متخصص یا ویدیوی متمرکز بر شغل. (مثلاً، "چگونه در سال ۲۰۲۴ یک شغل در علم داده پیدا کنیم").\n*   **هفته چهارم:** یک موضوع پیشرفته‌تر یا پرطرفدار. (مثلاً، "آیا ChatGPT می‌تواند به شما در یادگیری SQL کمک کند؟").\nبرای هر ویدیو، فرمت (مثلاً، "توضیح‌دهنده سخنگو،" "آموزش کدنویسی زنده") و CTA (مثلاً، "برای آموزش‌های بیشتر مشترک شوید،" "کد را از گیت‌هاب من دانلود کنید") را مشخص کنید.\n\n**محدودیت‌ها:** موضوعات باید برای مبتدیان مناسب اما جذاب باشند. از تنوع فرمت‌ها اطمینان حاصل کنید.`,
    tags_en: ['content strategy', 'youtube', 'data science'],
    tags_fa: ['استراتژی محتوا', 'یوتیوب', 'علم داده'],
  },
  {
    id: '9',
    title_en: 'Draft a Website Privacy Policy',
    title_fa: 'پیش‌نویس سیاست حفظ حریم خصوصی وب‌سایت',
    category: 'Legal',
    industry: 'E-commerce',
    role: 'Legal Advisor',
    prompt_en: `**Persona:** You are an AI assistant trained to draft basic legal documents. **Disclaimer: You are not a lawyer and this is not legal advice. The user should consult with a legal professional.**\n\n**Objective:** Draft a clear and simple privacy policy for a small e-commerce website that sells handmade crafts.\n\n**Task:** Generate a privacy policy document that includes the following sections:\n1.  **Introduction:** State the purpose of the policy.\n2.  **Information We Collect:** Specify the types of data collected (e.g., Personal Information like name/address for shipping, Payment Information processed by a third party like Stripe, Usage Data via cookies).\n3.  **How We Use Your Information:** Explain why the data is collected (e.g., to process orders, for customer support, for marketing communications with consent).\n4.  **Data Sharing:** Clarify with whom data might be shared (e.g., shipping partners, payment processors).\n5.  **Your Rights:** Briefly explain user rights (e.g., right to access or delete their data).\n6.  **Contact Us:** Provide a placeholder for contact information.\n\n**Constraints:** The language must be extremely simple and easy for a non-lawyer to understand. Avoid legal jargon where possible. Include a clear disclaimer at the top.`,
    prompt_fa: `**شخصیت:** شما یک دستیار هوش مصنوعی هستید که برای پیش‌نویس اسناد حقوقی اولیه آموزش دیده‌اید. **سلب مسئولیت: شما وکیل نیستید و این مشاوره حقوقی نیست. کاربر باید با یک متخصص حقوقی مشورت کند.**\n\n**هدف:** پیش‌نویس یک سیاست حفظ حریم خصوصی واضح و ساده برای یک وب‌سایت تجارت الکترونیک کوچک که صنایع دستی می‌فروشد، تهیه کنید.\n\n**وظیفه:** یک سند سیاست حفظ حریم خصوصی ایجاد کنید که شامل بخش‌های زیر باشد:\n۱. **مقدمه:** هدف از این سیاست را بیان کنید.\n۲. **اطلاعاتی که ما جمع‌آوری می‌کنیم:** انواع داده‌های جمع‌آوری شده را مشخص کنید (مثلاً، اطلاعات شخصی مانند نام/آدرس برای ارسال، اطلاعات پرداخت که توسط شخص ثالث مانند Stripe پردازش می‌شود، داده‌های استفاده از طریق کوکی‌ها).\n۳. **چگونه از اطلاعات شما استفاده می‌کنیم:** توضیح دهید که چرا داده‌ها جمع‌آوری می‌شوند (مثلاً، برای پردازش سفارشات، برای پشتیبانی مشتری، برای ارتباطات بازاریابی با رضایت).\n۴. **اشتراک‌گذاری داده‌ها:** روشن کنید که داده‌ها ممکن است با چه کسانی به اشتراک گذاشته شوند (مثلاً، شرکای حمل و نقل، پردازنده‌های پرداخت).\n۵. **حقوق شما:** به طور خلاصه حقوق کاربر را توضیح دهید (مثلاً، حق دسترسی یا حذف داده‌هایشان).\n۶. **تماس با ما:** یک جایگزین برای اطلاعات تماس ارائه دهید.\n\n**محدودیت‌ها:** زبان باید بسیار ساده و قابل فهم برای یک غیر وکیل باشد. در صورت امکان از اصطلاحات حقوقی خودداری کنید. یک سلب مسئولیت واضح در بالا قرار دهید.`,
    tags_en: ['privacy policy', 'legal', 'e-commerce'],
    tags_fa: ['سیاست حفظ حریم خصوصی', 'حقوقی', 'تجارت الکترونیک'],
  },
  {
    id: '10',
    title_en: 'Design a Scalable Microservices Architecture',
    title_fa: 'طراحی معماری میکروسرویس‌های مقیاس‌پذیر',
    category: 'Software Architecture',
    industry: 'Technology',
    role: 'Software Architect',
    prompt_en: `**Persona:** You are a seasoned Software Architect specializing in cloud-native applications.\n\n**Objective:** Design a high-level microservices architecture for a new social media platform.\n\n**Context:** The platform requires core features like user authentication, a news feed, a posting service (text and images), and a notification service.\n\n**Task:**\n1.  **Identify Microservices:** List and briefly describe the necessary microservices (e.g., \`Auth Service\`, \`User Profile Service\`, \`Post Service\`, \`Feed Generation Service\`, \`Notification Service\`).\n2.  **Communication Patterns:** For communication between services, recommend a primary pattern (e.g., asynchronous communication via a message broker like RabbitMQ or Kafka) and a secondary pattern for specific use cases (e.g., synchronous REST APIs for user authentication).\n3.  **Data Management:** Propose a database strategy. Recommend a database type for each service (e.g., "PostgreSQL for User Profile Service due to its relational nature," "Cassandra for Feed Service for high write throughput").\n4.  **API Gateway:** Explain the role of an API Gateway in this architecture.\n5.  **Diagram:** Describe the architecture in a way that could be translated into a diagram, explaining how the services interact through the API Gateway and message broker.\n\n**Constraints:** The design should prioritize scalability, resilience, and loose coupling. The output should be a well-structured technical document in Markdown.`,
    prompt_fa: `**شخصیت:** شما یک معمار نرم‌افزار باتجربه و متخصص در برنامه‌های بومی ابری (cloud-native) هستید.\n\n**هدف:** یک معماری میکروسرویس‌های سطح بالا برای یک پلتفرم رسانه اجتماعی جدید طراحی کنید.\n\n**زمینه:** این پلتفرم به ویژگی‌های اصلی مانند احراز هویت کاربر، فید خبری، سرویس ارسال پست (متن و تصویر) و سرویس اعلان نیاز دارد.\n\n**وظیفه:**\n۱. **شناسایی میکروسرویس‌ها:** میکروسرویس‌های لازم را فهرست کرده و به طور خلاصه توصیف کنید (مثلاً، \`سرویس احراز هویت\`، \`سرویس پروفایل کاربر\`، \`سرویس پست\`، \`سرویس تولید فید\`، \`سرویس اعلان\`).\n۲. **الگوهای ارتباطی:** برای ارتباط بین سرویس‌ها، یک الگوی اصلی (مثلاً، ارتباط ناهمزمان از طریق یک کارگزار پیام مانند RabbitMQ یا Kafka) و یک الگوی ثانویه برای موارد خاص (مثلاً، APIهای REST همزمان برای احراز هویت کاربر) توصیه کنید.\n۳. **مدیریت داده:** یک استراتژی پایگاه داده پیشنهاد دهید. نوع پایگاه داده را برای هر سرویس توصیه کنید (مثلاً، "PostgreSQL برای سرویس پروفایل کاربر به دلیل ماهیت رابطه‌ای آن،" "Cassandra برای سرویس فید برای توان عملیاتی نوشتن بالا").\n۴. **API Gateway:** نقش یک API Gateway در این معماری را توضیح دهید.\n۵. **نمودار:** معماری را به گونه‌ای توصیف کنید که بتوان آن را به یک نمودار تبدیل کرد، و توضیح دهید که چگونه سرویس‌ها از طریق API Gateway و کارگزار پیام با یکدیگر تعامل دارند.\n\n**محدودیت‌ها:** طراحی باید مقیاس‌پذیری، انعطاف‌پذیری و اتصال سست را در اولویت قرار دهد. خروجی باید یک سند فنی ساختاریافته در Markdown باشد.`,
    tags_en: ['microservices', 'architecture', 'backend'],
    tags_fa: ['میکروسرویس', 'معماری', 'بک‌اند'],
  },
];

export const INDUSTRIES = ['All', 'E-commerce', 'Technology', 'Finance', 'Healthcare', 'Education'];
export const ROLES = [
  'All', 
  'Marketing Manager', 
  'HR Specialist', 
  'DevOps Engineer', 
  'UX Designer', 
  'Technical Writer',
  'Financial Analyst',
  'Product Manager',
  'Content Creator',
  'Legal Advisor',
  'Software Architect'
];

export const translations: Translations = {
  en: {
    appName: 'A-Corp AI Academy',
    promptLibrary: 'Prompt Library',
    jsonGenerator: 'JSON Prompt Generator',
    searchPrompts: 'Search prompts...',
    industry: 'Industry',
    role: 'Role',
    all: 'All',
    viewPrompt: 'View Prompt',
    showDetails: 'Show Details',
    showLess: 'Show Less',
    generateJsonFromPrompt: 'Generate Structured JSON from a simple prompt.',
    enterPromptHere: 'e.g., "Generate social media campaign ideas for an eco-friendly product launch"',
    generateJson: 'Generate JSON',
    generating: 'Generating...',
    jsonOutput: 'JSON Output',
    copy: 'Copy',
    copied: 'Copied!',
    errorOccurred: 'An error occurred. Please try again.',
  },
  fa: {
    appName: 'آکادمی هوش مصنوعی A-Corp',
    promptLibrary: 'کتابخانه پرامپت',
    jsonGenerator: 'تولیدکننده پرامپت JSON',
    searchPrompts: 'جستجوی پرامپت‌ها...',
    industry: 'صنعت',
    role: 'نقش',
    all: 'همه',
    viewPrompt: 'مشاهده پرامپت',
    showDetails: 'نمایش جزئیات',
    showLess: 'نمایش کمتر',
    generateJsonFromPrompt: 'از یک پرامپت ساده، JSON ساختاریافته تولید کنید.',
    enterPromptHere: 'مثال: «ایده‌های کمپین رسانه‌های اجتماعی برای عرضه محصولی دوستدار محیط زیست تولید کن»',
    generateJson: 'تولید JSON',
    generating: 'در حال تولید...',
    jsonOutput: 'خروجی JSON',
    copy: 'کپی',
    copied: 'کپی شد!',
    errorOccurred: 'خطایی رخ داد. لطفا دوباره تلاش کنید.',
  },
};